/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BrandNewRouteImport } from './routes/brand-new'
import { Route as PreOwnedRouteImport } from './routes/pre-owned'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ApiPublicProductImageIdRouteImport } from './routes/api/public/product-image/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandNewRoute = BrandNewRouteImport.update({
  id: '/brand-new',
  path: '/brand-new',
  getParentRoute: () => rootRouteImport,
} as any)
const PreOwnedRoute = PreOwnedRouteImport.update({
  id: '/pre-owned',
  path: '/pre-owned',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProductImageIdRoute = ApiPublicProductImageIdRouteImport.update({
  id: '/api/public/product-image/$id',
  path: '/api/public/product-image/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/brand-new': typeof BrandNewRoute
  '/pre-owned': typeof PreOwnedRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/public/product-image/$id': typeof ApiPublicProductImageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/brand-new': typeof BrandNewRoute
  '/pre-owned': typeof PreOwnedRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/public/product-image/$id': typeof ApiPublicProductImageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/brand-new': typeof BrandNewRoute
  '/pre-owned': typeof PreOwnedRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/public/product-image/$id': typeof ApiPublicProductImageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/brand-new'
    | '/pre-owned'
    | '/reset-password'
    | '/api/public/product-image/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/brand-new'
    | '/pre-owned'
    | '/reset-password'
    | '/api/public/product-image/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/brand-new'
    | '/pre-owned'
    | '/reset-password'
    | '/api/public/product-image/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BrandNewRoute: typeof BrandNewRoute
  PreOwnedRoute: typeof PreOwnedRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicProductImageIdRoute: typeof ApiPublicProductImageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-new': {
      id: '/brand-new'
      path: '/brand-new'
      fullPath: '/brand-new'
      preLoaderRoute: typeof BrandNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pre-owned': {
      id: '/pre-owned'
      path: '/pre-owned'
      fullPath: '/pre-owned'
      preLoaderRoute: typeof PreOwnedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/product-image/$id': {
      id: '/api/public/product-image/$id'
      path: '/api/public/product-image/$id'
      fullPath: '/api/public/product-image/$id'
      preLoaderRoute: typeof ApiPublicProductImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BrandNewRoute: BrandNewRoute,
  PreOwnedRoute: PreOwnedRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicProductImageIdRoute: ApiPublicProductImageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
